update v2ray related packages
v2ray-core -> 4.40.0
v2ray-domain-list-community -> 20210606142051
v2ray-geoip -> 202106030115

diff --git a/net-proxy/v2ray-core/files/v2ray.initd b/net-proxy/v2ray-core/files/v2ray.initd
--- a/net-proxy/v2ray-core/files/v2ray.initd
+++ b/net-proxy/v2ray-core/files/v2ray.initd
@@ -1,19 +1,25 @@
 #!/sbin/openrc-run
 # Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
-command="/usr/bin/env V2RAY_LOCATION_ASSET="/etc/v2ray" /usr/bin/v2ray"
-command_args="-config /etc/v2ray/config.json"
+
+_CONF=${v2ray_conf:-/etc/v2ray/config.json}
+
+command="/usr/bin/env V2RAY_LOCATION_ASSET=/etc/v2ray /usr/bin/v2ray"
+command_args="-config ${_CONF}"
 command_args_background="true"
-pidfile="/run/v2ray.pid"
-start_stop_daemon_args="--background --make-pidfile --stderr /var/log/v2ray.log --stdout /var/log/v2ray.log"
+pidfile="/run/${RC_SVCNAME}.pid"
+start_stop_daemon_args="--background --make-pidfile --stderr /var/log/${RC_SVCNAME}.log --stdout /var/log/${RC_SVCNAME}.log"
 name="V2Ray Proxy Daemon"
 depend() {
 	need net
 }
 checkconfig() {
-	if [ ! -f /etc/v2ray/config.json ]; then
-		eerror "/etc/v2ray/config.json does not exist."
+	if [ ! -f "${_CONF}" ]; then
+		eerror "${_CONF} does not exist."
 	fi
+        if ! v2ray -test -c "${_CONF}" >/dev/null 2>&1; then
+                eerror "${_CONF} is invalid."
+        fi
 }
 start_pre() {
 	checkconfig || return 1
